### PR TITLE
License tests pep8

### PR DESCRIPTION
**Pull request by mroberge**
I made three commits (accept what you want!): 

1. added BSD license info in a couple of places

2. added a test directory and a few rudimentary tests. Run these from the command line like this: `python setup.py test`

3. I made minor modifications (spaces, mostly) to clean everything up for PEP8 style guides.

### CODE REVIEW

**Comment by mroberge** [comment]
Hi Stijn,
I'm a little new to collaborating on others' projects, so I don't know much about the etiquette. I figured I should start small, so I made some simple changes. Meanwhile, I have been working on a system in [hydrofunctions ](https://github.com/mroberge/hydrofunctions) for importing hydrology data from the USGS. This system will export a dataframe that should work with your HydroAnalysis object.

If you are interested in collaborating further, I would be happy to merge some of this code into hydropy, or whatever you are interested in.

**Comment by stijnvanhoey** [comment]
Thanks Martin! 
Good start on the testing environment and really nice work to make things pep8 compliant (I promise to have it as such for future implementations).

Concerning the LICENSE, this is basically covered by the provision of the file: https://github.com/stijnvanhoey/hydropy/blob/master/LICENSE but good to provide it in the readme and other places as well!

With respect to hydrofunctions/hydropy, I see two scenario's:
* We completely integrate these to libraries, and we extend (improve) the section https://github.com/stijnvanhoey/hydropy/blob/master/hydropy/reading_third_party_data.py with data loading functions for multiple partners
* We split the functionalities in two different packages: hydropy is the pandas-extension for hydrological time series analysis and hydrofunctions the package for data-retrieval from multiple partners. In this case, the naming `hydrofunctions` is maybe rather strange.

I opt for the complete integration in a single hydropy-package (for convenience), but I'm willing to discuss and converge differently.

**Comment by mroberge** [comment]
I'm all for integrating the two projects. Were you thinking a shared repository?

**Comment by stijnvanhoey** [comment]
You're now collaborator, so we can further work on it together. I propose to discuss implementations and features with issues. Merging this.

**Pull request merged**
